
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMENT EQUALS FLOAT IDENTIFIER NUMBER STRINGstatements : statements statement\n                  | statementstatement : IDENTIFIER EQUALS valuestatement : COMMENTvalue : NUMBER\n             | FLOAT\n             | STRING'
    
_lr_action_items = {'IDENTIFIER':([0,1,2,4,5,7,8,9,10,],[3,3,-2,-4,-1,-3,-5,-6,-7,]),'COMMENT':([0,1,2,4,5,7,8,9,10,],[4,4,-2,-4,-1,-3,-5,-6,-7,]),'$end':([1,2,4,5,7,8,9,10,],[0,-2,-4,-1,-3,-5,-6,-7,]),'EQUALS':([3,],[6,]),'NUMBER':([6,],[8,]),'FLOAT':([6,],[9,]),'STRING':([6,],[10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statements':([0,],[1,]),'statement':([0,1,],[2,5,]),'value':([6,],[7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statements","S'",1,None,None,None),
  ('statements -> statements statement','statements',2,'p_statements','parser.py',6),
  ('statements -> statement','statements',1,'p_statements','parser.py',7),
  ('statement -> IDENTIFIER EQUALS value','statement',3,'p_statement_assign','parser.py',15),
  ('statement -> COMMENT','statement',1,'p_statement_comment','parser.py',20),
  ('value -> NUMBER','value',1,'p_value','parser.py',25),
  ('value -> FLOAT','value',1,'p_value','parser.py',26),
  ('value -> STRING','value',1,'p_value','parser.py',27),
]
